### ISSUE TITLE
[Feature] API docs extension

### ISSUE THREAD

**Issue by danieldaeschle** [danieldaeschle/swapy#10]
## Description
Automatically creates a site (using Bulma) to show all API endpoints with documentation and endpoint testing.

## Todo
- [ ] Create page with bulma
- [ ] Implement scanning for py docs
- [ ] Site should provide authentication (if api has it)
- [ ] Site should provide testing endpoints
- [ ] Site should show description
- [ ] Site should show expected payload (by marshmallow)
