### ISSUE TITLE
Auto docs generation

### ISSUE THREAD

**Issue by danieldaeschle** [danieldaeschle/swapy#7]
## Description
Auto docs generation using pydomd and readthedocs template

## Todo
- [ ] Create scripts
- [x] Target to docs directory
- [x] Contain readme as index
- [ ] Contain quickstart
- [x] Contain pydoc
- [ ] Remove old docs
- [ ] Update docs to be compatible to pydocsmd
